# Generated by Django 6.0.6 on 2026-06-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnomalyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("service_name", models.CharField(db_index=True, max_length=128)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=16,
                    ),
                ),
                ("z_score", models.FloatField()),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("health_score", models.FloatField(blank=True, null=True)),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("webhook_triggered", models.BooleanField(default=False)),
                ("resolved", models.BooleanField(db_index=True, default=False)),
                ("ai_diagnosis", models.TextField(blank=True)),
                ("ai_diagnosed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Anomaly Event",
                "verbose_name_plural": "Anomaly Events",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "service_name",
                    models.CharField(db_index=True, default="default", max_length=128),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="INFO",
                        max_length=16,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("request_path", models.CharField(blank=True, max_length=512)),
                ("response_time_ms", models.FloatField(blank=True, null=True)),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Log Entry",
                "verbose_name_plural": "Log Entries",
                "ordering": ["-timestamp"],
                "permissions": [("view_watchdog", "Can view Watchdog APM dashboard")],
            },
        ),
        migrations.CreateModel(
            name="WebhookConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("url", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
                ("secret_token", models.CharField(blank=True, max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Webhook Config",
                "verbose_name_plural": "Webhook Configs",
                "ordering": ["-created_at"],
            },
        ),
    ]
