# Generated by Django 6.0.6 on 2026-06-18 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nocturne", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logentry",
            options={
                "ordering": ["-timestamp"],
                "permissions": [("view_watchdog", "Can view Watchdog APM")],
                "verbose_name": "Log Entry",
                "verbose_name_plural": "Log Entries",
            },
        ),
    ]
