# Generated by Django 6.0.6 on 2026-06-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nocturne", "0002_alter_logentry_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="ai_analysis",
            field=models.TextField(blank=True, null=True),
        ),
    ]
