# Generated by Django 6.0.6 on 2026-06-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nocturne", "0003_logentry_ai_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="ai_analysed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="logentry",
            name="exception_message",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="logentry",
            name="exception_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="logentry",
            name="stacktrace",
            field=models.TextField(blank=True, null=True),
        ),
    ]
