# Generated by Django 6.0.6 on 2026-06-19 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "nocturne",
            "0004_logentry_ai_analysed_at_logentry_exception_message_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("service_name", models.CharField(db_index=True, max_length=128)),
                ("health_score", models.FloatField()),
                ("error_rate", models.FloatField()),
                ("request_count", models.IntegerField()),
                ("anomaly_count", models.IntegerField()),
            ],
            options={
                "verbose_name": "Health Snapshot",
                "verbose_name_plural": "Health Snapshots",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["service_name", "recorded_at"],
                        name="watchdog_ap_service_47166c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("payload", models.JSONField(default=dict)),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                (
                    "anomaly",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_events",
                        to="nocturne.anomalyevent",
                    ),
                ),
                (
                    "webhook_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="nocturne.webhookconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Event",
                "verbose_name_plural": "Webhook Events",
                "ordering": ["-triggered_at"],
            },
        ),
    ]
