# Generated by Django 6.0.6 on 2026-06-19 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nocturne", "0005_healthsnapshot_webhookevent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logentry",
            options={
                "ordering": ["-timestamp"],
                "permissions": [("view_nocturne", "Can view Nocturne")],
                "verbose_name": "Log Entry",
                "verbose_name_plural": "Log Entries",
            },
        ),
        migrations.RenameIndex(
            model_name="healthsnapshot",
            new_name="nocturne_he_service_b85867_idx",
            old_name="watchdog_ap_service_47166c_idx",
        ),
    ]
